config:
    show_timestamps: true
    enable_channels: true
    log_path: '{path.log}/logger-{env.APP_MODE}'
defaults:
    handler_class: Monolog\Formatter\LineFormatter
    formatter_class: Monolog\Handler\StreamHandler
    formatter_format: '[%timestamp%] %channel%.%level_name%: %message% %context%'
logger:
    handlers:
        - print_writer
    processors:
        - timestamp
    filters: {  }
handlers:
    buffer_writer:
        class: Library\Logger\Writers\BufferWriter
        handlers:
            - print_writer
        processors: {  }
        extra_opt: /tmp/log.txt
    print_writer:
        class: Library\Logger\Writers\PrintWriter
        processors: {  }
        handlers: {  }
formatters:
    passthru:
        class: Library\Logger\Formatters\PassthruFormatter
        format: '[%timestamp%] %channel%.%level_name%: %message% %context%'
    line:
        class: Library\Logger\Formatters\LineFormatter
processors:
    tag:
        class: Library\Logger\Processors\TagProcessor
    hostname:
        class: Library\Logger\Processors\HostnameProcessor
    timestamp:
        class: Library\Logger\Processors\TimestampProcessor
filters:
    tag:
        class: Library\Logger\Filters\TagFilter
    level:
        class: Library\Logger\Filters\LevelFilter
    channel:
        class: Library\Logger\Filters\ChannelFilter
writers:
    name:
        class: null
        formatter: null
        handlers: {  }
        processors: {  }
cascade:
    name:
        class: null
